### ISSUE TITLE
auto detect kernel launch configuration doesnt work

### ISSUE THREAD

**Issue by ghost** [cbuchner1/CudaMiner#29]
cudaminer.exe -d 0 -i 1 -l auto -C 0 -o stratum+tcp://global.wemineltc.com:3335 -O myname:pw

i try to start the miner with this .bat. Unfortunately the programm crashes at the detection of the right kernel launch configuration, considering F0x0 is the right one for my GPU.

My GPU is a GTX 570. Could you tell me the right launch configuration for my GPU.

**Comment by cbuchner1** [comment]
I couldn't put this up for download to bitcointalk yet, because the forum
is down

Just get the 2013-12-01 release right here then and let me know if it fixes
the autotune issue for you.

https://mega.co.nz/#!BIx0mSJQ!DLngcULRwag5RjCMQFxgZB52RTorwW8FVqdUOkL71RU

2013/12/1 mistermin notifications@github.com

**Comment by ghost** [comment]
Ah, with the new Version it works fine, Thank You!
