### ISSUE TITLE
cannot connect to burnside Litecoin pool

### ISSUE THREAD

**Issue by Zedbloc** [cbuchner1/CudaMiner#8]
I'm using cudaminer on Linux Mint 14 Nadia, trying to connect to burnside's Litecoin pool. With these settings:

./cudaminer -o stratum+tcp://ltc-stratum.kattare.com:3333 -O [uname]:[pword]

I get the following output on the first run:

> Starting Stratum on stratum+tcp://ltc-stratum.kattare.com:3333
> thread 23719 create failed

And this output on the second run:

> Starting Stratum on stratum+tcp://ltc-stratum.kattare.com:3333
> Stratum authentication failed
> ...retry after 15 seconds
> thread 23724 create failed

The latest version of cudaminer says it has stratum support, so I don't need to use a proxy, right?

**Comment by cbuchner1** [comment]
The issue is with 64 bit builds, I presume. I've had the same issues on Ubuntu 12.04 64 bit

Running 32 bit binaries on a 64 Bit Linux will also work, so either cross-compile for 32 bit or build on a 32 bit machine and take the binaries to the new box. You will need 32 bit dependencies such as ia32-libs, and some i386 packages of libraries such as libcurl, libssl, maybe.

**Comment by cbuchner1** [comment]
I have not yet been able to confirm whether this is a bug that's already present upstream (in pooler's cpuminer) or whether this is a result of my cleanups so that the code compiles in C++ mode, too.

**Comment by Zedbloc** [comment]
Thank you, thus far. 

I'm almost able to compile a 32 bit build. However, the last few steps of the ./configure process result in:

> checking for the version of libcurl... 7.27.0
> checking for libcurl >= version 7.15.2... yes
> /usr/bin/curl-config: 138: /usr/bin/curl-config: CPPFLAG_CURL_STATICLIB: not found
> checking whether libcurl is usable... no
> configure: error: Missing required libcurl >= 7.15.2
